Repository alfianchii/confess, pull requests merged in 2023-03, with the labels that each got.

#5 feat: response crud
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/ComplaintController.php
  app/Http/Controllers/ResponseController.php
  app/Http/Kernel.php
  app/Http/Middleware/ResponseDashboard.php
  database/factories/ResponseFactory.php
  database/migrations/2023_03_01_131400_create_responses_table.php
  resources/js/sweetalert.js
  resources/js/sweetalert/swalMulti.js
  resources/js/sweetalert/swalSingle.js
  resources/views/dashboard/complaints/create.blade.php
  resources/views/dashboard/complaints/edit.blade.php
  resources/views/dashboard/complaints/index.blade.php
  resources/views/dashboard/complaints/show.blade.php
  resources/views/dashboard/responses/create.blade.php
  resources/views/dashboard/responses/edit.blade.php
  resources/views/dashboard/responses/index.blade.php
  resources/views/dashboard/responses/show.blade.php
  routes/web.php
Labels: enhancement

#31 fix: logo in sidebar dashboard
  resources/css/app.css
  resources/views/dashboard/layouts/sidebar.blade.php
Labels: type: bug

#35 fix: overflow background in mobile view
  resources/views/layouts/footer.blade.php
Labels: type: bug

#36 fix: bug darkmode in home page
  resources/css/app.css
Labels: type: bug

#46 skeleton loadings
  resources/js/dashboard.js
  resources/views/dashboard/index.blade.php
Labels: type: feature, type: improvement

#47 improvised response UI
  app/Http/Controllers/ResponseController.php
  resources/js/sweetalert.js
  resources/js/sweetalert/swalMulti.js
  resources/views/dashboard/complaints/show.blade.php
  resources/views/dashboard/index.blade.php
  resources/views/dashboard/responses/create.blade.php
  resources/views/dashboard/responses/index.blade.php
Labels: type: feature, type: improvement
